#!/bin/bash

if [ -d "$(pwd)/public" ]
then
	echo "public dir checked"
else
	ln -s ./cpp-node/public $(pwd)/public
fi

if [ -d "$(pwd)/temp" ]
then
	echo "temp dir checked"
else
	echo "creating temp directory"
	mkdir $(pwd)/temp
fi

cd ./mpm_lib

make build >&2

if [ $? -ne 0 ]
then
  echo "unable to build"
  cd ..
else
cd ..

cp  ./mpm_lib/lib/mpm-server.so.*.* ./CppNode/libs/shared

cd ./cpp-node&&make build>&2&&cd ..

if [ $? -ne 0 ]
then
  echo "Unabel to build CppNode"
else

  ./run 3000 $(pwd)
fi
fi
